[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

[lib]
name = "desktop_app_lib"
#crate-type = ["rlib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.2", features = [] }

[features]
compression = ["tauri/compression"]

[dependencies]
moss_env.workspace = true
moss_text.workspace = true
moss_desktop.workspace = true
moss_uikit.workspace = true
moss_cache.workspace = true

anyhow.workspace = true
once_cell.workspace = true
dirs.workspace = true
log.workspace = true
rand.workspace = true
fern.workspace = true
smol.workspace = true


# surrealdb = { workspace = true, features = ["kv-rocksdb"] }
tokio = { workspace = true, features = ["full", "macros", "signal"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
hashbrown = { workspace = true, features = ["serde"] }
smallvec.workspace = true
tauri.workspace = true

tauri-plugin-log = { version = "2.0.1", features = ["colored"] }
tauri-plugin-window-state = "2.0.1"
tauri-plugin-fs = "2.1.0"
tauri-plugin-global-shortcut = "2"
tauri-plugin-os = "2.2.0"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
mimalloc = { version = "0.1.39", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
cocoa = "0.26.0"
macos-trampoline = { path = "./lib/macos" }
