[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

[lib]
name = "app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
futures.workspace = true
anyhow.workspace = true
app.workspace = true
workspace.workspace = true

parking_lot.workspace = true
tracing.workspace = true

platform_window_tgui.workspace = true
platform_configuration_common.workspace = true
platform_formation_common.workspace = true

workbench_tgui.workspace = true
workbench_service_configuration_tgui.workspace = true

surrealdb = { workspace = true, features = ["kv-rocksdb"] }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
hashbrown = { workspace = true, features = ["serde"] }

tauri = { version = "2.0.0-rc", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0.0-rc"
tauri-plugin-os = "2.0.0-rc.0"

specta.workspace = true
specta-typescript = "0.0.7"
tauri-specta = { version = "2.0.0-rc.12", features = ["typescript"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
mimalloc = { version = "0.1.39", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
macos-trampoline = { path = "./lib/macos" }
