[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

[lib]
name = "app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
futures.workspace = true
anyhow.workspace = true
app.workspace = true
configuration.workspace = true
parking_lot.workspace = true
tracing.workspace = true
surrealdb = { workspace = true, features = ["kv-rocksdb"] }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
hashbrown = { workspace = true, features = ["serde"] }

specta = "2.0.0-rc.20"
specta-typescript = "0.0.7"

# tauri = { version = "2.0.0-rc.0", features = ["macos-private-api", "specta"] }
# # tauri-specta = { git = "https://github.com/oscartbeaumont/tauri-specta", rev = "a49885967adc01c80e33962e3ecac25fe7497839", features = [
# #     "typescript",
# # ] }


tauri-specta = { version = "2.0.0-rc.12", features = ["typescript"] }
tauri = { version = "2.0.0-rc", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0.0-rc"
# tauri-plugin-window = "2.0.0-alpha.2"
tauri-plugin-os = "2.0.0-rc.0"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
mimalloc = { version = "0.1.39", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
macos-trampoline = { path = "./lib/macos" }
