[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.17", features = [] }

[dependencies]
futures.workspace = true
anyhow.workspace = true
app.workspace = true
configuration.workspace = true
parking_lot.workspace = true
surrealdb = { workspace = true, features = ["kv-rocksdb"] }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
hashbrown = { workspace = true, features = ["serde"] }

specta = "=2.0.0-rc.12"
tauri = { version = "=2.0.0-beta.23", features = [ "macos-private-api", "specta"] }
tauri-specta = { git = "https://github.com/oscartbeaumont/tauri-specta", rev = "a49885967adc01c80e33962e3ecac25fe7497839", features = [
    "typescript",
] }
# tauri-specta = { version = "2.0.0-rc.11", features = ["typescript"] }
tracing.workspace = true


[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
mimalloc = { version = "0.1.39", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
macos-trampoline = { path = "./lib/macos" }
