[package]
name = "workbench_tgui"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sysinfo.workspace = true
specta.workspace = true
anyhow.workspace = true
hashbrown.workspace = true
lazy_static.workspace = true
tauri.workspace = true
once_cell.workspace = true

platform_core.workspace = true
platform_fs.workspace = true
platform_workspace.workspace = true
platform_formation.workspace = true
platform_configuration.workspace = true
platform_user_profile.workspace = true

workbench_service_configuration_tgui.workspace = true
workbench_service_user_profile_tgui.workspace = true
workbench_service_environment_tgui.workspace = true
