[package]
name = "workbench_tgui"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { workspace = true, features = ["derive"] }
specta.workspace = true

anyhow.workspace = true

platform_formation_common.workspace = true
platform_configuration_common.workspace = true
