version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: build(rust)
      prefix-development: chore(rust)
