github_actions:
  - changed-files:
      - any-glob-to-any-file: '.github/**'


jsonschema:
  - changed-files:
      - any-glob-to-any-file: 'assets/schemas'

makefile:
  - changed-files:
      - any-glob-to-any-file: 'Makefile'