repository:
  description: "Code Quality Monitoring Platform"

  default_branch: main
  issues: true
  wiki: false
  projects: false

  allow_merge_commit: true
  allow_squash_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

branches:
  main:
    protected: true
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: false
      require_code_owner_reviews: true
      authorized_actors_only: true
      authorized_actors:
        - "g10z3r"
    enforce_admins: false
