[package]
name = "goray"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["cli", "server"]


[dependencies]
cli = { path = "cli" }

anyhow = "1.0.81"
tokio = { version = "1.37.0", features = ["full"] }
