[workspace]
resolver = "2"
members = [
    "kernel/fs",

    "lib/moss_std",

    "platform/core",
    "platform/fs",
    "platform/formation",
    "platform/configuration",
    "platform/user_profile",
    "platform/environment",
    "platform/utl",
    "platform/workspace",
    "platform/app",

    "view/desktop/bin",

    "view/shared/workbench/tgui",
    "view/shared/workbench/service/configuration/common",
    "view/shared/workbench/service/configuration/tgui",
    "view/shared/workbench/service/user_profile/tgui",
    "view/shared/workbench/service/environment/tgui",

]

# [profile.dev]
# split-debuginfo = "unpacked"
# debug = "limited"
# codegen-units = 16

[profile.release]
debug = "limited"
lto = "thin"
codegen-units = 1


[workspace.dependencies]
fs = { path = "kernel/fs" }

moss_std = { path = "lib/moss_std" }

platform_core = { path = "platform/core" }
platform_utl = { path = "platform/utl" }
platform_configuration = { path = "platform/configuration" }
platform_formation = { path = "platform/formation" }
platform_user_profile = { path = "platform/user_profile" }
platform_environment = { path = "platform/environment" }
platform_workspace = { path = "platform/workspace" }
platform_fs = { path = "platform/fs" }

workbench_tgui = { path = "view/shared/workbench/tgui" }
workbench_service_configuration_common = { path = "view/shared/workbench/service/configuration/common" }
workbench_service_configuration_tgui = { path = "view/shared/workbench/service/configuration/tgui" }
workbench_service_user_profile_tgui = { path = "view/shared/workbench/service/user_profile/tgui" }
workbench_service_environment_tgui = { path = "view/shared/workbench/service/environment/tgui" }

project = { path = "platform/project" }

app = { path = "platform/app" }

tauri = "2.0.0-rc"
specta = "2.0.0-rc.20"
libc = "0.2.155"
fnv = "1.0.7"
thiserror = "1.0"
anyhow = "1.0"
chrono = "0.4"
notify = "6.1.1"
nanoid = "0.4"
hashbrown = "0.14.5"
ahash = "0.8.11"
arc-swap = "1.7.1"
radix_trie = "0.2.1"
parking_lot = "0.12.3"
derive_more = "0.99.17"
async-executor = "1.13"
strum = "0.26"
lazy-regex = "3.2.0"
dunce = "1.0.5"
sysinfo = "0.31.2"
tokio = "1"
tokio-util = "0.7"
tokio-stream = "0.1.15"
async-stream = "0.3.5"
smol = "2.0.0"
futures = "0.3"
async-task = "4.7.1"
flume = "0.11.0"
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
once_cell = "1.19"
lazy_static = "1.4.0"
surrealdb = "1.5.3"
tracing = "0.1"
opentelemetry = "0.22.0"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = "0.3.18"
slotmap = "1.0.7"
rustc-hash = "2.0.0"
parking = "2.2.1"
waker-fn = "1.2.0"
