[package]
name = "moss"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "kernel/disp",
    "kernel/fs",
    "lib/analysis",
    "lib/common",
    "lib/conf",
    "lib/dl",
    "lib/file",
    "mossctl",
    "net",
    "testdata/hello-wasm",
]

[profile.release]
# This makes the compiled code faster and smaller, but it makes 
# compiling slower, so it's only enabled in release mode.
lto = false
opt-level = 3
panic = "abort"
codegen-units = 1

[profile.dev.package.sqlx-macros]
opt-level = 3


[build]
rustflags = ["-C", "target-cpu=native"]

[workspace.dependencies]
fs = { path = "kernel/fs" }
disp = { path = "kernel/disp" }
chan = { path = "lib/chan" }
conf = { path = "lib/conf" }
dl = { path = "lib/dl" }
file = { path = "lib/file" }
common = { path = "lib/common" }
analysis = { path = "lib/analysis" }

mossctl = { path = "mossctl" }
net = { path = "net" }

anyhow = "1.0"
async-graphql = "7.0"
tokio = "1"
thiserror = "1.0"
async-trait = "0.1"
chrono = "0.4"
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
once_cell = "1.19"
tokio-util = "0.7"
tracing = "0.1"
sea-orm = "0.12"


[dependencies]
mossctl.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
once_cell.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
mimalloc = { version = "0.1.39", default-features = false }
