[package]
name = "moss"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["moss-cli", "moss-core", "moss-net"]


[dependencies]
moss-cli = { path = "moss-cli" }

anyhow = "1.0.81"
tokio = { version = "1", features = ["full"] }
