[package]
name = "workbench_service_configuration"
version = "0.1.0"
edition = "2021"


[dependencies]
configuration.workspace = true
workspace.workspace = true

serde_json.workspace = true
anyhow.workspace = true
