[package]
name = "moss_uikit"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
moss_text.workspace = true
moss_html.workspace = true

serde = { workspace = true, features = ["derive", "rc"] }
ts-rs.workspace = true

[lints]
workspace = true