[package]
name = "moss_uikit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { workspace = true, features = ["derive", "rc"] }
ts-rs.workspace = true
