[package]
name = "workbench_service_user_profile_tao"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
arc-swap.workspace = true

platform_user_profile.workspace = true
platform_fs.workspace = true
