[package]
name = "workbench_service_theme"
version = "0.1.0"
edition = "2021"

[dependencies]
desktop_models.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
indexmap = { workspace = true, features = ["serde"] }
