[package]
name = "fs"
version = "0.1.0"
edition = "2021"


[dependencies]
libc.workspace = true
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full", "sync"] }
smol.workspace = true
notify.workspace = true
