[package]
name = "moss_html"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
moss_str.workspace = true

serde = { workspace = true, features = ["derive", "rc"] }
ts-rs.workspace = true
