[package]
name = "sys"
version = "0.1.0"
edition = "2021"


[dependencies]
chan.workspace = true
anyhow.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full", "sync"] }
notify = "6.1.1"
