[package]
name = "bindexp"
description = "Export TS bindongs from Rust code."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moss_uikit.workspace = true

anyhow.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tauri-specta = { version = "2.0.0-rc.12", features = ["typescript"] }
