[package]
name = "bus"
version = "0.1.0"
edition = "2021"


[dependencies]
types.workspace = true
anyhow.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["full", "signal", "macros"] }
