licenses = ["LICENSE-MIT"]

[rust_workspace_audit.ignore]
desktop = [
    "tauri-plugin-shell",
    "tauri-plugin-os",
    "tauri-specta",
    "tauri-plugin-fs",
    "tauri-plugin-log",
    "tauri-plugin-clipboard-manager",
    "tauri-plugin-window-state"
]

xtask = [
    "cargo_metadata",
    "clap",
    "pathdiff",
    "toml"
]