[addon]
id = "theme-defaults"
name = "Moss Default Themes"
categories = ["Themes"]

[contributes]
themes = [
  { label = "Moss Dark Default", path = "themes/moss-dark.css" },
  { label = "Moss Light Default", path = "themes/moss-light.css" },
]
