[package]
name = "platform_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moss_env.workspace = true
slotmap.workspace = true
parking_lot.workspace = true
derive_more.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
futures.workspace = true
smol.workspace = true
async-task.workspace = true
flume.workspace = true
parking.workspace = true
waker-fn.workspace = true
once_cell.workspace = true
smallvec.workspace = true
dyn-clone.workspace = true
async-trait.workspace = true
hashbrown = { workspace = true, features = [] }
radix_trie.workspace = true
rustc-hash.workspace = true
im.workspace = true
serde = { workspace = true, features = ["derive"] }

[features]
default = []
