[package]
name = "desktop_models"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
moss_str.workspace = true
uikit_models.workspace = true

serde = { workspace = true, features = ["derive", "rc"] }
ts-rs.workspace = true
once_cell.workspace = true
