[package]
name = "desktop_models"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
moss_str.workspace = true
moss_uikit.workspace = true
moss_jsonlogic.workspace = true

indexmap = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive", "rc"] }
ts-rs = { workspace = true, features = ["indexmap-impl", "serde-json-impl"] }
once_cell.workspace = true
csscolorparser.workspace = true
serde_json.workspace = true
jsonschema.workspace = true
