[package]
name = "base"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow.workspace = true
async-task.workspace = true
flume.workspace = true
smol.workspace = true
once_cell.workspace = true
async-trait.workspace = true
