[package]
name = "qme"
version = "0.1.0"
edition = "2021"
description = "Quality Monitoring Engine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
