[package]
name = "workbench_desktop"
version = "0.1.0"
edition = "2021"

[features]
compression = ["tauri/compression"]

[dependencies]
moss_text.workspace = true
moss_uikit.workspace = true
moss_html.workspace = true
moss_jsonlogic.workspace = true
moss_jsonlogic_macro.workspace = true
moss_desktop.workspace = true

quote.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
hashbrown.workspace = true
lazy_static.workspace = true
tauri.workspace = true
once_cell.workspace = true
slotmap.workspace = true
derive_more.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
os_info.workspace = true
gethostname.workspace = true

platform_core.workspace = true
platform_fs.workspace = true
platform_workspace.workspace = true
platform_formation.workspace = true
platform_configuration.workspace = true
platform_user_profile.workspace = true

workbench_service_configuration_tao.workspace = true
workbench_service_user_profile_tao.workspace = true
workbench_service_environment_tao.workspace = true
