[package]
name = "moss_tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
moss_desktop.workspace = true

tauri.workspace = true
serde.workspace = true
tauri-runtime-wry = "2.2.0"
derive_more = { workspace = true, features = ["full"] }
