name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test-suite:
    name: Rust Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2.7.5
        with:
          workspaces: ".github/cache"

      - name: Cache Apt Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            libwebkit2gtk-4.0-dev
            libwebkit2gtk-4.1-dev
            libappindicator3-dev
            librsvg2-dev
            patchelf

      - name: Run Unit Tests
        run: cargo -q test --lib
        working-directory: ".github/cache"

      - name: Run Documentation Tests
        if: always()
        run: cargo -q test --doc
        working-directory: ".github/cache"

  rust-dependency-audit:
    name: Rust Dependency Audit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2.7.5
        with:
          workspaces: ".github/cache"

      - name: Cache Apt Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            libwebkit2gtk-4.0-dev
            libwebkit2gtk-4.1-dev
            libappindicator3-dev
            librsvg2-dev
            patchelf

      - name: Audit Rust Workspace Dependencies
        run: |
          cd tools/xtask
          cargo -q run -- --fail-fast rwa

  node-workflows:
    name: Node.js Workflows - ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - name: lint
            command: pnpm run lint -- --quiet
          - name: test-packages
            command: pnpm run test --project packages
          - name: test-desktop
            command: pnpm run test --project desktop
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Execute Task - ${{ matrix.task.name }}
        run: ${{ matrix.task.command }}
