[package]
name = "workbench"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot.workspace = true
anyhow.workspace = true
hashbrown = { workspace = true, features = ["serde"] }

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
